# $Id: application.yml 154 2009-07-02 17:03:32Z feby $
common: &default_settings
  email_from: webmster@yourdomain.com
  email_from_name: "Do not reply - yourwebsite.com" 
  smtp_user_name: yourgmailaccount
  smtp_password: yourgmailpassword
  application_name: yourwebsite.com
  
development:
  <<: *default_settings
  site_url: localhost:3000
  
  
test:
  <<: *default_settings
  site_url: localhost:3000

production:
  <<: *default_settings
  site_url: yourdomain.com
  
